### ISSUE TITLE
Set margin-left and margin-right to auto

### ISSUE THREAD

**Issue by Dragas** [bitonic/mazzo.li#11]
Your statically rendered site tends to fall on the side on screens that are larger than 1100px in width. Would it be possible to set the following css properties on `div.article#wrapper`?

```css
div.wrapper#article {
    margin-left: auto;
    margin-right: auto;
}
```
